#[M_calculator]
#"latest" = {git="https://github.com/urbanjost/M_calculator"}

#[M_CLI]
#"latest" = {git="https://github.com/urbanjost/M_CLI"}

#[M_CLI2]
#"latest" = {git="https://github.com/urbanjost/M_CLI2"}

#[M_color]
#"latest" = {git="https://github.com/urbanjost/M_color"}

#[M_draw]
#"latest" = {git="https://github.com/urbanjost/M_draw"}

#[M_escape]
#"latest" = {git="https://github.com/urbanjost/M_escape"}

#[M_history]
#"latest" = {git="https://github.com/urbanjost/M_history"}

#[M_io]
#"latest" = {git="https://github.com/urbanjost/M_io"}

#[M_kracken95]
#"latest" = {git="https://github.com/urbanjost/M_kracken95"}

#[M_msg]
#"latest" = {git="https://github.com/urbanjost/M_msg"}

#[M_pixel]
#"latest" = {git="https://github.com/urbanjost/M_pixel"}

#[M_process]
#"latest" = {git="https://github.com/urbanjost/M_process"}

#[M_strings]
#   "latest" = {git="https://github.com/urbanjost/M_strings"}

#[M_system]
#   "latest" = {git="https://github.com/urbanjost/M_system"}

#[M_time]
#"latest" = {git="https://github.com/urbanjost/M_time"}
############################################################################################################
# THIS WAS RENAMED. NEED TO UPDATE IN REGISTRY
#[M_change]
#"latest" = {git="https://github.com/urbanjost/M_change"}
############################################################################################################
[M_uuid]
"latest" = {git="https://github.com/urbanjost/M_uuid"}

[M_intrinsics]
"latest" = {git="https://github.com/urbanjost/M_intrinsics"}

[fpm-man]
"latest" = {git="https://github.com/urbanjost/fpm-man"}
############################################################################################################

#drwxrwxr-x 11 urbanjs urbanjs 4096 Mar 17 20:11 /home/urbanjs/venus/V600/github/M_BRE
#drwxrwxrwx 12 urbanjs urbanjs 4096 Mar 17 17:53 /home/urbanjs/venus/V600/github/M_calcomp
#drwxrwxrwx  7 urbanjs urbanjs 4096 Mar 15 00:17 /home/urbanjs/venus/V600/github/M_curl
#drwxrwxrwx  9 urbanjs urbanjs 4096 Mar 15 00:17 /home/urbanjs/venus/V600/github/M_evaluate
#drwxrwxrwx  3 urbanjs urbanjs 4096 Jan 12 22:33 /home/urbanjs/venus/V600/github/M_generic_linked_list
#drwxrwxrwx  9 urbanjs urbanjs 4096 Mar 15 00:17 /home/urbanjs/venus/V600/github/M_html
#drwxrwxrwx  5 urbanjs urbanjs 4096 Mar 10 16:48 /home/urbanjs/venus/V600/github/M_kracken2015
#drwxrwxrwx 10 urbanjs urbanjs 4096 Mar 10 16:48 /home/urbanjs/venus/V600/github/M_list
#drwxrwxrwx 11 urbanjs urbanjs 4096 Mar 17 18:24 /home/urbanjs/venus/V600/github/M_match
#drwxrwxrwx 11 urbanjs urbanjs 4096 Mar 10 16:48 /home/urbanjs/venus/V600/github/M_ncurses
#drwxrwxrwx  9 urbanjs urbanjs 4096 Mar 15 00:17 /home/urbanjs/venus/V600/github/M_path
#drwxrwxrwx 10 urbanjs urbanjs 4096 Mar 10 16:49 /home/urbanjs/venus/V600/github/M_readline
#drwxrwxrwx 10 urbanjs urbanjs 4096 Mar 15 00:17 /home/urbanjs/venus/V600/github/M_slices
#drwxrwxrwx 10 urbanjs urbanjs 4096 Mar 15 00:17 /home/urbanjs/venus/V600/github/M_sort
#drwxrwxrwx  2 urbanjs urbanjs 4096 Feb  8 20:26 /home/urbanjs/venus/V600/github/M_xml
